export function generateOperationalReport(rawNotes: string) {
  const cleanedNotes = rawNotes.trim();

  if (!cleanedNotes) {
    return "";
  }

  const today = new Date().toLocaleDateString();

  return `SKIPPEROS OPERATIONAL REPORT

Report Date:
${today}

Raw Captain Notes:
${cleanedNotes}

Trip Summary:
A vessel operation was recorded based on the captain's notes. The notes should be reviewed and confirmed by the skipper or operator before being used for official compliance, safety, maintenance, or business records.

Operational Details Identified:
- Departure and return information should be confirmed.
- Crew count should be confirmed.
- Fuel levels should be checked and recorded.
- Weather and sea conditions should be noted if relevant.
- Any mechanical issues, safety concerns, damage, or unusual events should be logged.

Maintenance Follow-Up:
If the notes mention leaks, engine issues, overheating, vibration, battery problems, pump issues, hull damage, fuel problems, steering problems, or electrical faults, a maintenance task should be created.

Incident Follow-Up:
If the notes mention injury, damage, near miss, unsafe conditions, collision, grounding, equipment failure, or emergency response, an incident report should be created.

Compliance Note:
This report was generated from rough operational notes. The operator should verify all information before submitting it for inspection, compliance, insurance, client reporting, or internal records.

Professional Log:
${cleanedNotes}

Generated by SkipperOS`;
}